trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  - group: xamarin-android-aab
  - name: buildConfiguration
    value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_6_0
  displayName: "Select the Xamarin SDK version"
  enabled: true

- task: DownloadSecureFile@1
  name: keyStore
  displayName: "Download keystore from secure files"
  inputs:
    secureFile: production.jks

- task: Bash@3
  displayName: "Build and sign App Bundle"
  inputs:
    targetType: "inline"
    script: |
      msbuild -restore $(Build.SourcesDirectory)/XamarinAndroidAab/*.csproj -t:SignAndroidPackage -p:AndroidPackageFormat=aab -p:Configuration=$(buildConfiguration) -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=$(keyStore.secureFilePath) -p:AndroidSigningStorePass=$(keystore.password) -p:AndroidSigningKeyAlias=$(key.alias) -p:AndroidSigningKeyPass=$(key.password)

- task: CopyFiles@2
  displayName: 'Copy deliverables'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/XamarinAndroidAab/bin/$(buildConfiguration)'
    Contents: '*.aab'
    TargetFolder: 'drop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish release'
  inputs:
    pathToPublish: 'drop'
    artifactName: 'release'

- task: InstallBundletool@1
  inputs:
    username: 'damienaicheh'
    personalAccessToken: '$(githubPersonnalAccessToken)'

- task: AabConvertToUniversalApk@1
  inputs:
    aabFilePath: '$(Build.SourcesDirectory)/XamarinAndroidAab/bin/$(buildConfiguration)/*.aab'
    keystoreFilePath: '$(keyStore.secureFilePath)'
    keystorePassword: '$(keystore.password)'
    keystoreAlias: '$(key.alias)'
    keystoreAliasPassword: '$(key.password)'
    outputFolder: '$(Build.SourcesDirectory)/tmp'

- task: AppCenterDistribute@3
  displayName: 'Distribute to Visual Studio App Center'
  inputs:
    serverEndpoint: 'VSAC'
    appSlug: $(appSlug)
    appFile: '$(Build.SourcesDirectory)/tmp/*.apk'
    releaseNotesOption: 'input'
    releaseNotesInput: 'New Version'
    destinationType: 'groups'
    distributionGroupId: $(distributionGroupId)
